from .auth_routes   import auth_bp
from .user_routes   import user_bp
from .doctor_routes import doctor_bp
from .utils_routes  import utils_bp
from .appointment_routes import appointment_bp
from .consultation_routes import consultation_bp
from .chat_routes import chat_bp
from .v2_routes import v2_bp
from .messages_routes import messages_bp
from .report_routes import reports_bp
from .payment_routes import payment_bp
from .ai_v2_routes import ai_v2_bp
