import React, { useState, useRef, useEffect } from 'react';
import { API_BASE_URL } from '../../utils/config';
import { handleError } from '../../utils/error_handlers';

export default function ReportUpload() {
    const [reports, setReports] = useState([]);
    const [dragOver, setDragOver] = useState(false);
    const [uploading, setUploading] = useState(false);
    const [analysing, setAnalysing] = useState(false);
    const [selected, setSelected] = useState(null);
    const [showResult, setShowResult] = useState(false);
    const [loading, setLoading] = useState(true);
    const fileRef = useRef(null);

    const fetchReports = async () => {
        try {
            const token = localStorage.getItem('token') || sessionStorage.getItem('token');
            const res = await fetch(`${API_BASE_URL}/api/reports`, {
                headers: { 'Authorization': `Bearer ${token}` }
            });
            const json = await res.json();
            if (res.ok) {
                setReports(json.reports || []);
            }
        } catch (err) {
            handleError(err, 'Failed to fetch reports');
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchReports();
    }, []);

    const handleFiles = async (files) => {
        const file = files[0];
        if (!file) return;
        const allowed = ['application/pdf', 'image/jpeg', 'image/png', 'image/jpg'];
        if (!allowed.includes(file.type)) { alert('Only PDF, JPG, PNG allowed.'); return; }
        if (file.size > 20 * 1024 * 1024) { alert('File must be under 20 MB.'); return; }

        setUploading(true);
        try {
            const token = localStorage.getItem('token') || sessionStorage.getItem('token');
            const formData = new FormData();
            formData.append('file', file);
            formData.append('displayName', file.name.replace(/\.[^.]+$/, ''));

            const res = await fetch(`${API_BASE_URL}/api/reports`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${token}` },
                body: formData
            });
            const json = await res.json();
            if (res.ok) {
                fetchReports(); // Refresh list
            } else {
                alert(json.error || 'Upload failed');
            }
        } catch (err) {
            handleError(err, 'Upload failed');
        } finally {
            setUploading(false);
        }
    };

    const handleDrop = (e) => { e.preventDefault(); setDragOver(false); handleFiles(e.dataTransfer.files); };
    
    const handleAnalyse = async (report) => {
        setAnalysing(true);
        setSelected(report);
        setShowResult(true); // Open modal in loading state
        
        try {
            const token = localStorage.getItem('token') || sessionStorage.getItem('token');
            const res = await fetch(`${API_BASE_URL}/api/reports/${report.id}/analyze`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${token}` }
            });
            const json = await res.json();
            if (res.ok) {
                setSelected({ ...report, ...json.data });
                fetchReports(); // Update status in list
            } else {
                alert(json.error || 'Analysis failed');
                setShowResult(false);
            }
        } catch (err) {
            handleError(err, 'Analysis failed');
            setShowResult(false);
        } finally {
            setAnalysing(false);
        }
    };

    const handleDownload = (report) => {
        const content = [
            '=================================================',
            `  VaidyaMed-X Medical Report`,
            '=================================================',
            `Report Name : ${report.name}`,
            `Date        : ${report.date}`,
            `File Size   : ${report.size}`,
            `Status      : ${report.status}`,
            '-------------------------------------------------',
            '',
            'SUMMARY',
            report.summary || 'Summary not Available',
            '',
            'AYURVEDIC INSIGHTS',
            report.ayurvedic || 'Insights not Available',
            '',
            'FOLLOW-UP RECOMMENDATION',
            'No critical values detected. Recommended follow-up in 3 months.',
            '',
            '=================================================',
            'Generated by VaidyaMed-X Health Platform',
            `Downloaded on: ${new Date().toLocaleString('en-IN')}`,
            '=================================================',
        ].join('\n');

        const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${report.name.replace(/\s+/g, '_')}_Report.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div>
            <div className="pd-page-header">
                <div>
                    <h1>📄 Medical Reports</h1>
                    <p>Upload your lab reports for instant AI analysis with Ayurvedic insights</p>
                </div>
            </div>

            {/* Upload Zone */}
            <div
                className={`pd-upload-zone ${dragOver ? 'drag-over' : ''}`}
                style={{ marginBottom: 24 }}
                onDragOver={e => { e.preventDefault(); setDragOver(true); }}
                onDragLeave={() => setDragOver(false)}
                onDrop={handleDrop}
                onClick={() => fileRef.current?.click()}
            >
                <div className="pd-upload-icon">{uploading ? '⏳' : '📤'}</div>
                <div className="pd-upload-title">
                    {uploading ? 'Uploading report…' : 'Drag & drop your report here'}
                </div>
                <div className="pd-upload-sub">
                    {uploading
                        ? 'Please wait, our AI is processing your document'
                        : 'Supports PDF, JPG, PNG • Max 20 MB • Lab reports, prescriptions, X-rays'}
                </div>
                {!uploading && (
                    <button className="pd-btn pd-btn-primary" style={{ marginTop: 16 }} onClick={e => { e.stopPropagation(); fileRef.current?.click(); }}>
                        📁 Browse Files
                    </button>
                )}
                <input ref={fileRef} type="file" className="pd-upload-file-input" accept=".pdf,.jpg,.jpeg,.png"
                    onChange={e => handleFiles(e.target.files)} />
            </div>

            {/* Reports Table */}
            <div className="pd-card">
                <h3 className="pd-section-title">📋 Your Reports</h3>
                {reports.length === 0 ? (
                    <div className="pd-empty"><div className="pd-empty-icon">📭</div><h3>No reports yet</h3><p>Upload your first report above.</p></div>
                ) : (
                    <div className="pd-table-wrap">
                        <table className="pd-report-table">
                            <thead>
                                <tr>
                                    <th>Report</th><th>Date</th><th>Size</th><th>Status</th><th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {reports.map(r => (
                                    <tr key={r.id}>
                                        <td>
                                            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                                                <span>📄</span>
                                                <div>
                                                    <div style={{ fontWeight: 600 }}>{r.name}</div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>{r.date}</td>
                                        <td>{r.size || '---'}</td>
                                        <td><span className={`pd-pill ${r.status === 'Analysed' ? 'pd-pill-green' : 'pd-pill-gold'}`}>{r.status}</span></td>
                                        <td>
                                            <div style={{ display: 'flex', gap: 6 }}>
                                                <button className="pd-btn pd-btn-primary pd-btn-sm"
                                                    onClick={() => handleAnalyse(r)}
                                                    disabled={r.status === 'Processing' || analysing}>
                                                    🤖 AI Analyse
                                                </button>
                                                <button className="pd-btn pd-btn-outline pd-btn-sm"
                                                    onClick={() => handleDownload(r)}>
                                                    📥 Download
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>

            {/* AI Analysis Result Modal */}
            {showResult && selected && (
                <div style={{
                    position: 'fixed', inset: 0, background: 'rgba(10,30,15,0.60)',
                    backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center',
                    justifyContent: 'center', zIndex: 1000, padding: 20
                }} onClick={() => setShowResult(false)}>
                    <div style={{
                        background: '#fff', borderRadius: 20, padding: 36, maxWidth: 560, width: '100%',
                        boxShadow: '0 24px 64px rgba(10,40,20,0.35)'
                    }} onClick={e => e.stopPropagation()}>
                        <div style={{ fontSize: '2rem', marginBottom: 6 }}>🔬</div>
                        <h2 style={{ fontFamily: 'Playfair Display, serif', color: '#2d6a4f', marginBottom: 4 }}>
                            AI Analysis: {selected.name}
                        </h2>
                        {analysing ? (
                            <div style={{ textAlign: 'center', padding: '30px 0' }}>
                                <div style={{ fontSize: '2rem', marginBottom: 10 }}>⏳</div>
                                <p style={{ color: '#6b8f71' }}>Analysing with AI…</p>
                            </div>
                        ) : (
                            <>
                                <div style={{ background: '#f4faf6', borderRadius: 12, padding: 16, marginTop: 14 }}>
                                    <strong style={{ color: '#2d6a4f', fontSize: '0.84rem' }}>📊 Medical Summary</strong>
                                    <p style={{ fontSize: '0.86rem', color: '#3d5c3d', marginTop: 6, lineHeight: 1.7 }}>{selected.summary || selected['Medical Summary']}</p>
                                </div>
                                <div style={{ background: '#fff8e7', borderRadius: 12, padding: 16, marginTop: 12 }}>
                                    <strong style={{ color: '#996b10', fontSize: '0.84rem' }}>🌿 Ayurvedic Insights</strong>
                                    <p style={{ fontSize: '0.86rem', color: '#5c4a0a', marginTop: 6, lineHeight: 1.7 }}>{selected.ayurvedic || selected['Ayurvedic Insights']}</p>
                                </div>
                                <div style={{ background: '#eafaf1', borderRadius: 12, padding: 16, marginTop: 12 }}>
                                    <strong style={{ color: '#1e8449', fontSize: '0.84rem' }}>✅ Follow-Up</strong>
                                    <p style={{ fontSize: '0.86rem', color: '#1e8449', marginTop: 6 }}>No critical values detected. Recommended follow-up in 3 months.</p>
                                </div>
                            </>
                        )}
                        <button className="pd-btn pd-btn-primary" style={{ marginTop: 20, width: '100%', justifyContent: 'center' }}
                            onClick={() => setShowResult(false)}>Close</button>
                    </div>
                </div>
            )}
        </div>
    );
}

